# 1. Create a 3x3x3 array with random values 

In [16]:
import numpy as np
np.empty((3,3,3))

array([[[6.23042070e-307, 3.56043053e-307, 1.60219306e-306],
        [7.56571288e-307, 1.89146896e-307, 1.37961302e-306],
        [1.05699242e-307, 8.01097889e-307, 1.78020169e-306]],

       [[7.56601165e-307, 1.02359984e-306, 1.33510679e-306],
        [2.22522597e-306, 1.33511018e-306, 6.23057689e-307],
        [1.33511290e-306, 1.78019082e-306, 8.45559303e-307]],

       [[8.06613040e-308, 6.89810244e-307, 1.22387550e-307],
        [2.22522596e-306, 8.34423917e-308, 1.11261162e-306],
        [1.78021527e-306, 1.11260619e-306, 5.08887615e-322]]])

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [17]:
np.diag(1+np.arange(4), k = -1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [18]:
array= np.array([[0,1], [1,0]])
Z = np.tile(array,(4,4))
print (Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [19]:
x= np.random.random((5,5))
print("Original Array:")
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print("After normalization:")
print(x)

Original Array:
[[0.17883109 0.69330217 0.70211499 0.43773141 0.12329233]
 [0.62969195 0.76138221 0.38270801 0.95546067 0.70418925]
 [0.09379512 0.57995084 0.60636191 0.039629   0.89849046]
 [0.33228751 0.00375759 0.74612284 0.71119594 0.98233168]
 [0.08677719 0.48193328 0.15348954 0.04323646 0.49838672]]
After normalization:
[[0.17890675 0.70464218 0.71364796 0.44347569 0.12215196]
 [0.63963921 0.77421283 0.38724755 0.97254065 0.71576763]
 [0.09200891 0.58880902 0.61579836 0.03665682 0.91432307]
 [0.3357231  0.         0.75861936 0.72292773 1.        ]
 [0.08483732 0.48864537 0.15301034 0.04034326 0.50545906]]


# 5.  How to find common values between two arrays?

In [20]:
a = np.random.randint(0,10,10)
b = np.random.randint(0,10,10)

np.intersect1d(a, b)

array([2, 3, 6, 8, 9])

# 6.How to get the dates of yesterday, today and tomorrow?

In [21]:
yest = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tom  = np.datetime64('today') + np.timedelta64(1)
print(yest, today, tom)

2021-06-29 2021-06-30 2021-07-01


# 7. Consider two random array A and B, check if they are equal

In [22]:
a=np.random.random((3,3))
b=np.random.random((3,3))
if a.all()==b.all():
    print('They are equal')
else:
    print('They are not equal')

They are equal


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [23]:
a = np.random.rand(10)
a[a.argmax()] = 0
a

array([0.43293849, 0.18842978, 0.64101158, 0.32302591, 0.        ,
       0.88524357, 0.58257434, 0.45622168, 0.8396199 , 0.58061663])

# 9. How to print all the values of an array?

In [24]:
a=np.random.random((2,2))
print(a)

[[0.97031431 0.70215973]
 [0.48270022 0.73046989]]


# 10.Subtract the mean of each row of a matrix

In [25]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
m1=a[0].mean()
m2=a[1].mean()
m3=a[2].mean()
print(m1-m2-m3)

-11.0


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [26]:
a = np.ones(5)
b = np.random.randint(0, len(a), 10)
a += np.bincount(b, minlength = len(a))
a

array([3., 4., 2., 3., 3.])

# 12.How to get the diagonal of a dot product?

In [27]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(0,10,(3,3))

np.einsum("ij,ji->i", a, b)

array([ 87,  26, 142])

# 13.How to find the most frequent value in an array?

In [28]:
a = np.random.randint(0,10,20)
print(a)
max(set(a), key = list(a).count)

[1 9 3 7 1 6 5 1 2 3 8 9 5 1 4 3 0 1 8 7]


1

# 14.How to get the n largest values of an array

In [29]:
a=np.random.random((3,3))
print(a.max())

0.9406621975078405


# 15.How to create a record array from a regular array?

In [30]:
arr = np.array([("Science", 88.5, 90),
                 ("Maths", 87, 99),
             ("English", 85.5, 91)])

print(arr)
print("\nRECORD ARRAY")
record = np.core.records.fromarrays(arr.T,
                              names='col1, col2, col3',
                              formats = 'S80, f8, i8')
record

[['Science' '88.5' '90']
 ['Maths' '87' '99']
 ['English' '85.5' '91']]

RECORD ARRAY


rec.array([(b'Science', 88.5, 90), (b'Maths', 87. , 99),
           (b'English', 85.5, 91)],
          dtype=[('col1', 'S80'), ('col2', '<f8'), ('col3', '<i8')])